<?php

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreOrderRequest;
use App\Models\Item;
use App\Models\Order;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Inertia\Inertia;
use Inertia\Response;

class OrderController extends Controller
{
    /**
     * Show Checkout Page for an item
     */
    public function checkout(Item $item): Response|RedirectResponse
    {
        if (! $item->is_purchasable || $item->status !== 'published') {
            return redirect()->route('home')->with('error', 'This item is not currently available for direct purchase. Please request a quote.');
        }

        $item->load('category');

        return Inertia::render('Public/Checkout', [
            'item' => $item,
        ]);
    }

    /**
     * Store new order with server-verified price
     */
    public function store(StoreOrderRequest $request): RedirectResponse
    {
        $validated = $request->validated();
        $item = Item::findOrFail($validated['item_id']);

        if (! $item->is_purchasable || $item->status !== 'published') {
            return back()->with('error', 'Item is not available for purchase.');
        }

        // Server-recomputed amount — never trust client input
        $amount = $item->price ?? 0.00;
        $transactionId = 'TXN-' . strtoupper(Str::random(10));
        $user = $request->user();

        // Ensure user is registered as a CRM Client
        $client = \App\Models\Client::firstOrCreate(
            ['email' => $user->email],
            [
                'name' => $user->name,
                'phone' => $user->phone,
                'contact_person' => $user->name,
                'status' => 'active',
            ]
        );

        $order = Order::create([
            'user_id' => $user->id,
            'client_id' => $client->id,
            'item_id' => $item->id,
            'amount' => $amount,
            'currency' => 'BDT',
            'status' => 'paid',
            'payment_method' => $validated['payment_method'],
            'transaction_id' => $transactionId,
        ]);

        return redirect()->route('profile.edit')->with('success', "Order #{$order->id} placed successfully! Transaction ID: {$transactionId}");
    }

    /**
     * Customer pays a pending order / invoice generated by Admin
     */
    public function payPending(Request $request, Order $order): RedirectResponse
    {
        if ($order->user_id !== $request->user()->id) {
            abort(403, 'Unauthorized access to this order.');
        }

        $validated = $request->validate([
            'payment_method' => ['required', 'string', 'max:50'],
            'transaction_id' => ['nullable', 'string', 'max:150'],
        ]);

        $txn = !empty($validated['transaction_id']) 
            ? $validated['transaction_id'] 
            : 'TXN-' . strtoupper(Str::random(10));

        $order->update([
            'status' => 'paid',
            'payment_method' => $validated['payment_method'],
            'transaction_id' => $txn,
        ]);

        return redirect()->route('profile.edit')->with('success', 'Payment submitted successfully! Your invoice is now marked as Paid.');
    }

    /**
     * Client Dashboard & Order History redirects to unified Profile Hub
     */
    public function dashboard(Request $request): RedirectResponse
    {
        return redirect()->route('profile.edit');
    }
}
